version: "3"
services:
  app:
    build: /home/circleci/sample
    expose:
      - "3000"
  waiter:
    image: waisbrot/wait
    environment:
      TARGETS: "app:3000"
      TIMEOUT: 300
    depends_on:
      - app
  casper:
    image: vitr/casperjs
    depends_on: 
      - waiter
    command: casperjs test --initial-url="http://app:3000" --xunit=log.xml /home/circleci/tests/webapp-tests.js
    
      
